### ISSUE TITLE
Player spawns on the hub

### ISSUE THREAD

**Issue by luluwaza** [IGLADI/Ethereal-Hyperspace-Battleships#1]
C4MPU5 K441

**Comment by ThomasKnoops** [comment]
I take this issue over while you fix the database @HGThinh

**Comment by ThomasKnoops** [comment]
With the addition of the database, this was erased... You now start on the planet of your guild instead of C4MPU5 K441 where the tutorial is...

**Comment by LordTlasT** [comment]
> With the addition of the database, this was erased... You now start on the planet of your guild instead of C4MPU5 K441 where the tutorial is...
