### ISSUE TITLE
Energy consumption

### ISSUE THREAD

**Issue by luluwaza** [IGLADI/Ethereal-Hyperspace-Battleships#11]
Add energy depletion with specific actions such as combat

**Comment by luluwaza** [comment]
#14 #43 #12

**Comment by ThomasKnoops** [comment]
why #43? Deze wordt toch op fuel gedaan? niet op energy..

**Comment by IGLADI** [comment]
> why #43? Deze wordt toch op fuel gedaan? niet op energy..

men gaat een space warp & normale travel implementeren.
