### ISSUE TITLE
riddles and puzzles

### ISSUE THREAD

**Issue by luluwaza** [IGLADI/Ethereal-Hyperspace-Battleships#22]
Will have to be resolved by sharing information with eachother within a certain amount of time.
Some players get info others don't

**Comment by ThomasKnoops** [comment]
Right now there is only one sort of event:
"locate a lost ship" --> will only show on the radar when closeby --> Only 10 minutes time to search everywhere from (-100,-100) to (100,100) so IMPOSSIBLE when alone or when you don't communicate with the other participants...
