### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by luluwaza** [IGLADI/Ethereal-Hyperspace-Battleships#27]
The database will be local, this is easy for testing.
Code must function with this database ex: `/register`.
Documentation of the databse at [EtHB-docs](https://github.com/LordTlasT/EtHB-docs/database)

**Comment by HGThinh** [comment]
Database
etherealhyperspacebattleships
Table
1 Resources
Table to store resources information: id, resources_id, resources_name, resources_capacity, resources_quantity

2 Money
Table to store currency information: id, guild_id, guild_name, currency_capacity, guild_leader

3 Guilds
Table to store guilds's information: id, guild_id, guild_name, guild_capacity, guild_leader

4 Space ship
Table to store spaceship information: id,  spaceship_id, spaceship_name, spaceship_capacity, guild_name, user_name

5 Users
Table to store users information: id, user_id, username, guild_name, user_class

**Comment by HGThinh** [comment]
![guild_table](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/assets/132908713/ae7b88af-c74f-4e26-a1e5-7baa05ea456a)

**Comment by HGThinh** [comment]
[DatabaseProjectX.txt](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/files/13649731/DatabaseProjectX.txt)

**Comment by LordTlasT** [comment]
There is a database from now on! [#dc5e98](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/commit/dc5e98baabf4a5d24463e5d46d52dca322b4413d)
