### ISSUE TITLE
Create main guild roles

### ISSUE THREAD

**Issue by IGLADI** [IGLADI/Ethereal-Hyperspace-Battleships#28]
The auto created channels per main guild will be locked for ppl not in this guild, should also only allow officers to host stages in stage channels (meeting room).
see: [Text/voice discord channels](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/issues/6) 

Also see:
[Main Guild](https://github.com/IGLADI/IT-project-Ethereal-Hyperspace-Battleships/issues/5)

**Comment by luluwaza** [comment]
#5
