### ISSUE TITLE
/help command

### ISSUE THREAD

**Issue by luluwaza** [IGLADI/Ethereal-Hyperspace-Battleships#45]
Displays all the most important commands in the game such as:
- /guild which displays it's own info panel about the guild
- /combat which displays it's own info panel about combat
- /resource which display it's own info panel about resources 
- /coordinates which displays the most important coordinates (such as main hub and guild HQ)
- /money which displays the possible ways to make money
- other helpful comands that might be implemented in the future

**Comment by luluwaza** [comment]
#5 
#10 
#12 
#14 
#15

**Comment by IGLADI** [comment]
Should implement different help commands per functionality: one for combat, one for guilds, one global,...
