### ISSUE TITLE
Add AI generated pictures

### ISSUE THREAD

**Issue by IGLADI** [IGLADI/Ethereal-Hyperspace-Battleships#58]
Using Leonardo AI => at least generate a picture when arriving on a planet (once a planets picture has been generated it's stored and reused to reduce costs & add coherence) and display them to the player each time he arrives at a planet.
Later on other AI generated pictures/(music/narrator in voc) will be added

**Comment by ThomasKnoops** [comment]
After feedback from Robin: We will be creating some images (only did 12 right now, this can be done after the project) and save them in the db...
--> We will be saving the image itself in an assets folder and saving the path to the image in the db!
