### ISSUE TITLE
Fix max cargo capacity using module

### ISSUE THREAD

**Issue by IGLADI** [IGLADI/Ethereal-Hyperspace-Battleships#86]
![image](https://github.com/IGLADI/Ethereal-Hyperspace-Battleships/assets/128155180/f501b8fa-76a1-47f4-a2b7-b9dca4d7e896)

**Comment by LordTlasT** [comment]
Proabably because the amounts are updated not within add_cargo() function and editing player.ship.modules["Cargo"].resources["Copper"] directly or something alike. 

The best way to fix this is by using add_cargo wherever possible and change add_cargo to a setter for the resources property in Cargo
